
- name: Add Prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Install Prometheus binaries and config
  shell: |
    mv /opt/prometheus-*/prometheus /usr/local/bin/
    mv /opt/prometheus-*/promtool /usr/local/bin/
    mkdir -p /etc/prometheus /var/lib/prometheus
    cp -r /opt/prometheus-*/consoles /etc/prometheus/
    cp -r /opt/prometheus-*/console_libraries /etc/prometheus/
    chown -R prometheus:prometheus /etc/prometheus /var/lib/prometheus
    sudo apt update
    sudo apt install pipx
    pipx ensurepath #Modifie le chemin d'installation de PVE Exporter, se base sur le PATH dans le env
    pipx install prometheus-pve-exporter

- name: Add Prometheus config
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']


        - job_name: 'pve_exporter'
          static_configs:
            - targets: ['localhost:9221']


        - job_name: 'pve'
          static_configs:
            - targets:
                - 62.210.245.189
          metrics_path: /pve
          params:
            module: [default]
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: 127.0.0.1:9221

#        - job_name: 'pve_nodes'
#          static_configs:
#            - targets:
#                - 62.210.245.189:9100
#                - 62.210.204.67:9100
#                - 195.154.167.4:9100
#                - 62.210.246.144:9100

- name: Create Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus \
        --web.listen-address=:9090

      [Install]
      WantedBy=multi-user.target


- name: Create systemd service for prometheus-pve-exporter
  copy:
    dest: /etc/systemd/system/pve-exporter.service
    content: |
      [Unit]
      Description=Prometheus PVE Exporter
      After=network.target

      [Service]
      ExecStart=/home/azureuser/.local/bin/pve_exporter \
        --config /etc/prometheus/pve.yml \
        --web.listen-address=0.0.0.0:9221
      Restart=always
      User=azureuser

      [Install]
      WantedBy=multi-user.target
  become: yes


- name: Enable and start pve-exporter
  systemd:
    name: pve-exporter
    daemon_reload: yes
    enabled: yes
    state: started
  become: yes

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    daemon_reload: yes
    enabled: yes
    state: started
